### PR TITLE
Added PHP

### PR DESCRIPTION
**Pull request by gricey432**

### CODE REVIEW

**Comment by TRManderson** [comment]
My benchmarks to compare:

Haskell:
```
benchmarking quicksort - sorted - 1..1000
time                 13.72 ms   (13.36 ms .. 14.10 ms)
                     0.992 R²   (0.986 R² .. 0.998 R²)
mean                 13.84 ms   (13.59 ms .. 14.18 ms)
std dev              753.3 μs   (495.5 μs .. 1.092 ms)
variance introduced by outliers: 22% (moderately inflated)

benchmarking quicksort - sorted - 1..2000
time                 58.95 ms   (56.20 ms .. 61.47 ms)
                     0.993 R²   (0.983 R² .. 0.999 R²)
mean                 59.96 ms   (58.78 ms .. 61.65 ms)
std dev              2.385 ms   (1.653 ms .. 3.377 ms)

benchmarking quicksort - sorted - 1..4000
time                 277.4 ms   (248.2 ms .. 302.8 ms)
                     0.997 R²   (0.995 R² .. 1.000 R²)
mean                 280.4 ms   (274.8 ms .. 287.7 ms)
std dev              7.213 ms   (3.479 ms .. 9.515 ms)
variance introduced by outliers: 16% (moderately inflated)

benchmarking quicksort - sorted - 1..8000
time                 1.198 s    (1.072 s .. 1.303 s)
                     0.999 R²   (0.995 R² .. 1.000 R²)
mean                 1.210 s    (1.185 s .. 1.229 s)
std dev              28.84 ms   (0.0 s .. 32.70 ms)
variance introduced by outliers: 19% (moderately inflated)
```

PHP:
```
Sorted 1000 elements in 0.028108s
Sorted 2000 elements in 0.108018s
Sorted 4000 elements in 0.428440s
Sorted 8000 elements in 1.728287s
```

**Comment by nick-potts** [comment]
Here's how my system performs, updated with compiler optimisations where possible:

Rust -O:
```
Sorted 1000 elements in 725us
Sorted 2000 elements in 2ms
Sorted 4000 elements in 9ms
Sorted 8000 elements in 39ms
```

Python:
```
Sorted 1000 elements in 0.0756120681763s
Sorted 2000 elements in 0.296247959137s
Sorted 4000 elements in 1.14178204536s
Sorted 8000 elements in 4.68279504776s
```

php7.1:
```
Sorted 1000 elements in 0.036873s
Sorted 2000 elements in 0.133948s
Sorted 4000 elements in 0.530212s
Sorted 8000 elements in 2.070703s
```

Swift -Ounchecked:
```
Benchmark time for 1000 items: 0.000397026538848877
Benchmark time for 2000 items: 0.00167000293731689
Benchmark time for 4000 items: 0.00634199380874634
Benchmark time for 8000 items: 0.0286819934844971
```

Haskell:
```
benchmarking quicksort/sorted - 1..1000
time                 15.62 ms   (14.53 ms .. 17.24 ms)
                     0.961 R²   (0.934 R² .. 0.982 R²)
mean                 15.80 ms   (15.18 ms .. 16.44 ms)
std dev              1.604 ms   (1.395 ms .. 1.982 ms)
variance introduced by outliers: 48% (moderately inflated)

benchmarking quicksort/sorted - 1..2000
time                 70.25 ms   (65.67 ms .. 73.64 ms)
                     0.986 R²   (0.942 R² .. 0.997 R²)
mean                 66.13 ms   (62.06 ms .. 69.60 ms)
std dev              6.593 ms   (4.925 ms .. 8.646 ms)
variance introduced by outliers: 34% (moderately inflated)

benchmarking quicksort/sorted - 1..4000
time                 276.0 ms   (246.5 ms .. 314.4 ms)
                     0.994 R²   (0.992 R² .. 1.000 R²)
mean                 284.7 ms   (274.3 ms .. 292.5 ms)
std dev              10.95 ms   (5.788 ms .. 15.19 ms)
variance introduced by outliers: 16% (moderately inflated)

benchmarking quicksort/sorted - 1..8000
time                 1.124 s    (921.3 ms .. 1.228 s)
                     0.996 R²   (0.990 R² .. 1.000 R²)
mean                 1.079 s    (1.026 s .. 1.109 s)
std dev              47.08 ms   (0.0 s .. 52.37 ms)
variance introduced by outliers: 19% (moderately inflated)
```

**Comment by LightAndLight** [comment]
@email4nickp 

I think your system is whacked bro

**Comment by nick-potts** [comment]
whatcha mean @LightAndLight

**Comment by LightAndLight** [comment]
Don't worry, you fixed the Rust times

**Comment by nick-potts** [comment]
yeah I needed compiler optimisations on

**Comment by nick-potts** [comment]
C -O3:
```
Sorted 1000 elements in 0.000496 seconds
Sorted 2000 elements in 0.001193 seconds
Sorted 4000 elements in 0.007170 seconds
Sorted 8000 elements in 0.022041 seconds
```

**Comment by gricey432** [comment]
@email4nickp what version of python is that with?

**Pull request merged**
